
version: '3'
services:
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: "phpmyadmin"
    ports:
      - "88:80"
    depends_on:
      - "db"
    networks: 
      - dev-network
  db:
    image: "mysql:5.6"
    container_name: "mysql5.6"
    volumes:
      - ./test/init.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    networks: 
      - dev-network

  mongo:  # 会自动从Docker Hub上自动获取mongo这个镜像
    image: 'mongo'
    container_name: 'mongo_server'
    restart: always
    volumes:
      - ./data:/data/db/
    ports:
      - 27017:27017  # 本地端口(可自定义):容器内默认端口(mongo设定为27017)
    environment:  # admin账号和密码
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks: 
      - dev-network
  manager:
    # mongodb://admin:admin@127.0.0.1
    image: 'mrvautin/adminmongo'
    restart: always
    ports:
      - 1234:1234
    environment:
      CONN_NAME: manager
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_HOST: mongo
      DB_PORT: 27017
    depends_on:
      - 'mongo'
    networks: 
      - dev-network

networks:
  dev-network: 