
version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'mongo_server'
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - dev-network
  manager:
    image: 'yfsoftcom/adminmongo'
    restart: always
    ports:
      - 1234:1234
    environment:
      CONN_NAME: manager
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_HOST: mongo
      DB_PORT: 27017
    depends_on:
      - 'mongo'
    networks:
      - dev-network

networks:
  dev-network: